/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsRouteImport } from './routes/us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CaRouteImport } from './routes/ca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as UsIndexRouteImport } from './routes/us/index'
import { Route as UsFaqRouteImport } from './routes/us/faq'
import { Route as UsArticlesIndexRouteImport } from './routes/us/articles/index'
import { Route as UsArticlesSlugRouteImport } from './routes/us/articles/$slug'

const UsRoute = UsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CaRoute = CaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsIndexRoute = UsIndexRouteImport.update({
  id: '/us/',
  path: '/',
  getParentRoute: () => UsRoute,
} as any)
const UsFaqRoute = UsFaqRouteImport.update({
  id: '/us/faq',
  path: '/faq',
  getParentRoute: () => UsRoute,
} as any)
const UsArticlesIndexRoute = UsArticlesIndexRouteImport.update({
  id: '/us/articles/',
  path: '/articles/',
  getParentRoute: () => UsRoute,
} as any)
const UsArticlesSlugRoute = UsArticlesSlugRouteImport.update({
  id: '/us/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => UsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/us': typeof UsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/us/': typeof UsIndexRoute
  '/us/faq': typeof UsFaqRoute
  '/us/articles/': typeof UsArticlesIndexRoute
  '/us/articles/$slug': typeof UsArticlesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/us': typeof UsIndexRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/us/faq': typeof UsFaqRoute
  '/us/articles/$slug': typeof UsArticlesSlugRoute
  '/us/articles': typeof UsArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/us': typeof UsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/us/': typeof UsIndexRoute
  '/us/faq': typeof UsFaqRoute
  '/us/articles/': typeof UsArticlesIndexRoute
  '/us/articles/$slug': typeof UsArticlesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ca'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/us'
    | '/articles/$slug'
    | '/articles/'
    | '/us/'
    | '/us/faq'
    | '/us/articles/'
    | '/us/articles/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ca'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/us'
    | '/articles/$slug'
    | '/articles'
    | '/us/faq'
    | '/us/articles/$slug'
    | '/us/articles'
  id:
    | '__root__'
    | '/'
    | '/ca'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/us'
    | '/articles/$slug'
    | '/articles/'
    | '/us/'
    | '/us/faq'
    | '/us/articles/'
    | '/us/articles/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaRoute: typeof CaRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UsRoute: typeof UsRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

export interface UsRouteChildren {
  UsIndexRoute: typeof UsIndexRoute
  UsFaqRoute: typeof UsFaqRoute
  UsArticlesIndexRoute: typeof UsArticlesIndexRoute
  UsArticlesSlugRoute: typeof UsArticlesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/us': {
      id: '/us'
      path: '/us'
      fullPath: '/us'
      preLoaderRoute: typeof UsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca': {
      id: '/ca'
      path: '/ca'
      fullPath: '/ca'
      preLoaderRoute: typeof CaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us/': {
      id: '/us/'
      path: '/'
      fullPath: '/us/'
      preLoaderRoute: typeof UsIndexRouteImport
      parentRoute: typeof UsRouteImport
    }
    '/us/faq': {
      id: '/us/faq'
      path: '/faq'
      fullPath: '/us/faq'
      preLoaderRoute: typeof UsFaqRouteImport
      parentRoute: typeof UsRouteImport
    }
    '/us/articles/': {
      id: '/us/articles/'
      path: '/articles'
      fullPath: '/us/articles/'
      preLoaderRoute: typeof UsArticlesIndexRouteImport
      parentRoute: typeof UsRouteImport
    }
    '/us/articles/$slug': {
      id: '/us/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/us/articles/$slug'
      preLoaderRoute: typeof UsArticlesSlugRouteImport
      parentRoute: typeof UsRouteImport
    }
  }
}

const usRouteChildren: UsRouteChildren = {
  UsIndexRoute: UsIndexRoute,
  UsFaqRoute: UsFaqRoute,
  UsArticlesIndexRoute: UsArticlesIndexRoute,
  UsArticlesSlugRoute: UsArticlesSlugRoute,
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaRoute: CaRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UsRoute: UsRoute._addFileChildren(usRouteChildren),
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
