/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsRouteImport } from './routes/us'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpdeskRouteImport } from './routes/helpdesk'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaRouteImport } from './routes/ca'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsIndexRouteImport } from './routes/us/index'
import { Route as HelpdeskIndexRouteImport } from './routes/helpdesk/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as UsFaqRouteImport } from './routes/us/faq'
import { Route as UsContactRouteImport } from './routes/us/contact'
import { Route as HelpdeskSupportRouteImport } from './routes/helpdesk/support'
import { Route as HelpdeskIdeasRouteImport } from './routes/helpdesk/ideas'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardRoadmapRouteImport } from './routes/dashboard/roadmap'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardReceiptsRouteImport } from './routes/dashboard/receipts'
import { Route as DashboardMileageRouteImport } from './routes/dashboard/mileage'
import { Route as DashboardHomeOfficeRouteImport } from './routes/dashboard/home-office'
import { Route as DashboardFileManagerRouteImport } from './routes/dashboard/file-manager'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as UsArticlesIndexRouteImport } from './routes/us/articles/index'
import { Route as UsArticlesSlugRouteImport } from './routes/us/articles/$slug'

const UsRoute = UsRouteImport.update({
  id: '/us',
  path: '/us',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpdeskRoute = HelpdeskRouteImport.update({
  id: '/helpdesk',
  path: '/helpdesk',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaRoute = CaRouteImport.update({
  id: '/ca',
  path: '/ca',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsIndexRoute = UsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsRoute,
} as any)
const HelpdeskIndexRoute = HelpdeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpdeskRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsFaqRoute = UsFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => UsRoute,
} as any)
const UsContactRoute = UsContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => UsRoute,
} as any)
const HelpdeskSupportRoute = HelpdeskSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => HelpdeskRoute,
} as any)
const HelpdeskIdeasRoute = HelpdeskIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => HelpdeskRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoadmapRoute = DashboardRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReceiptsRoute = DashboardReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMileageRoute = DashboardMileageRouteImport.update({
  id: '/mileage',
  path: '/mileage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHomeOfficeRoute = DashboardHomeOfficeRouteImport.update({
  id: '/home-office',
  path: '/home-office',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFileManagerRoute = DashboardFileManagerRouteImport.update({
  id: '/file-manager',
  path: '/file-manager',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UsArticlesIndexRoute = UsArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => UsRoute,
} as any)
const UsArticlesSlugRoute = UsArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => UsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/helpdesk': typeof HelpdeskRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/us': typeof UsRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/file-manager': typeof DashboardFileManagerRoute
  '/dashboard/home-office': typeof DashboardHomeOfficeRoute
  '/dashboard/mileage': typeof DashboardMileageRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/helpdesk/ideas': typeof HelpdeskIdeasRoute
  '/helpdesk/support': typeof HelpdeskSupportRoute
  '/us/contact': typeof UsContactRoute
  '/us/faq': typeof UsFaqRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/helpdesk/': typeof HelpdeskIndexRoute
  '/us/': typeof UsIndexRoute
  '/us/articles/$slug': typeof UsArticlesSlugRoute
  '/us/articles/': typeof UsArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/file-manager': typeof DashboardFileManagerRoute
  '/dashboard/home-office': typeof DashboardHomeOfficeRoute
  '/dashboard/mileage': typeof DashboardMileageRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/helpdesk/ideas': typeof HelpdeskIdeasRoute
  '/helpdesk/support': typeof HelpdeskSupportRoute
  '/us/contact': typeof UsContactRoute
  '/us/faq': typeof UsFaqRoute
  '/articles': typeof ArticlesIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/helpdesk': typeof HelpdeskIndexRoute
  '/us': typeof UsIndexRoute
  '/us/articles/$slug': typeof UsArticlesSlugRoute
  '/us/articles': typeof UsArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ca': typeof CaRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/helpdesk': typeof HelpdeskRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/us': typeof UsRouteWithChildren
  '/articles/$slug': typeof ArticlesSlugRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/file-manager': typeof DashboardFileManagerRoute
  '/dashboard/home-office': typeof DashboardHomeOfficeRoute
  '/dashboard/mileage': typeof DashboardMileageRoute
  '/dashboard/receipts': typeof DashboardReceiptsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/roadmap': typeof DashboardRoadmapRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/helpdesk/ideas': typeof HelpdeskIdeasRoute
  '/helpdesk/support': typeof HelpdeskSupportRoute
  '/us/contact': typeof UsContactRoute
  '/us/faq': typeof UsFaqRoute
  '/articles/': typeof ArticlesIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/helpdesk/': typeof HelpdeskIndexRoute
  '/us/': typeof UsIndexRoute
  '/us/articles/$slug': typeof UsArticlesSlugRoute
  '/us/articles/': typeof UsArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ca'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/helpdesk'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/us'
    | '/articles/$slug'
    | '/dashboard/billing'
    | '/dashboard/file-manager'
    | '/dashboard/home-office'
    | '/dashboard/mileage'
    | '/dashboard/receipts'
    | '/dashboard/reports'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/helpdesk/ideas'
    | '/helpdesk/support'
    | '/us/contact'
    | '/us/faq'
    | '/articles/'
    | '/dashboard/'
    | '/helpdesk/'
    | '/us/'
    | '/us/articles/$slug'
    | '/us/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ca'
    | '/contact'
    | '/faq'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/articles/$slug'
    | '/dashboard/billing'
    | '/dashboard/file-manager'
    | '/dashboard/home-office'
    | '/dashboard/mileage'
    | '/dashboard/receipts'
    | '/dashboard/reports'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/helpdesk/ideas'
    | '/helpdesk/support'
    | '/us/contact'
    | '/us/faq'
    | '/articles'
    | '/dashboard'
    | '/helpdesk'
    | '/us'
    | '/us/articles/$slug'
    | '/us/articles'
  id:
    | '__root__'
    | '/'
    | '/ca'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/helpdesk'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/us'
    | '/articles/$slug'
    | '/dashboard/billing'
    | '/dashboard/file-manager'
    | '/dashboard/home-office'
    | '/dashboard/mileage'
    | '/dashboard/receipts'
    | '/dashboard/reports'
    | '/dashboard/roadmap'
    | '/dashboard/settings'
    | '/helpdesk/ideas'
    | '/helpdesk/support'
    | '/us/contact'
    | '/us/faq'
    | '/articles/'
    | '/dashboard/'
    | '/helpdesk/'
    | '/us/'
    | '/us/articles/$slug'
    | '/us/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaRoute: typeof CaRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  HelpdeskRoute: typeof HelpdeskRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UsRoute: typeof UsRouteWithChildren
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/us': {
      id: '/us'
      path: '/us'
      fullPath: '/us'
      preLoaderRoute: typeof UsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/helpdesk': {
      id: '/helpdesk'
      path: '/helpdesk'
      fullPath: '/helpdesk'
      preLoaderRoute: typeof HelpdeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ca': {
      id: '/ca'
      path: '/ca'
      fullPath: '/ca'
      preLoaderRoute: typeof CaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us/': {
      id: '/us/'
      path: '/'
      fullPath: '/us/'
      preLoaderRoute: typeof UsIndexRouteImport
      parentRoute: typeof UsRoute
    }
    '/helpdesk/': {
      id: '/helpdesk/'
      path: '/'
      fullPath: '/helpdesk/'
      preLoaderRoute: typeof HelpdeskIndexRouteImport
      parentRoute: typeof HelpdeskRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us/faq': {
      id: '/us/faq'
      path: '/faq'
      fullPath: '/us/faq'
      preLoaderRoute: typeof UsFaqRouteImport
      parentRoute: typeof UsRoute
    }
    '/us/contact': {
      id: '/us/contact'
      path: '/contact'
      fullPath: '/us/contact'
      preLoaderRoute: typeof UsContactRouteImport
      parentRoute: typeof UsRoute
    }
    '/helpdesk/support': {
      id: '/helpdesk/support'
      path: '/support'
      fullPath: '/helpdesk/support'
      preLoaderRoute: typeof HelpdeskSupportRouteImport
      parentRoute: typeof HelpdeskRoute
    }
    '/helpdesk/ideas': {
      id: '/helpdesk/ideas'
      path: '/ideas'
      fullPath: '/helpdesk/ideas'
      preLoaderRoute: typeof HelpdeskIdeasRouteImport
      parentRoute: typeof HelpdeskRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/roadmap': {
      id: '/dashboard/roadmap'
      path: '/roadmap'
      fullPath: '/dashboard/roadmap'
      preLoaderRoute: typeof DashboardRoadmapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/receipts': {
      id: '/dashboard/receipts'
      path: '/receipts'
      fullPath: '/dashboard/receipts'
      preLoaderRoute: typeof DashboardReceiptsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mileage': {
      id: '/dashboard/mileage'
      path: '/mileage'
      fullPath: '/dashboard/mileage'
      preLoaderRoute: typeof DashboardMileageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/home-office': {
      id: '/dashboard/home-office'
      path: '/home-office'
      fullPath: '/dashboard/home-office'
      preLoaderRoute: typeof DashboardHomeOfficeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/file-manager': {
      id: '/dashboard/file-manager'
      path: '/file-manager'
      fullPath: '/dashboard/file-manager'
      preLoaderRoute: typeof DashboardFileManagerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/us/articles/': {
      id: '/us/articles/'
      path: '/articles'
      fullPath: '/us/articles/'
      preLoaderRoute: typeof UsArticlesIndexRouteImport
      parentRoute: typeof UsRoute
    }
    '/us/articles/$slug': {
      id: '/us/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/us/articles/$slug'
      preLoaderRoute: typeof UsArticlesSlugRouteImport
      parentRoute: typeof UsRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardFileManagerRoute: typeof DashboardFileManagerRoute
  DashboardHomeOfficeRoute: typeof DashboardHomeOfficeRoute
  DashboardMileageRoute: typeof DashboardMileageRoute
  DashboardReceiptsRoute: typeof DashboardReceiptsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRoadmapRoute: typeof DashboardRoadmapRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardFileManagerRoute: DashboardFileManagerRoute,
  DashboardHomeOfficeRoute: DashboardHomeOfficeRoute,
  DashboardMileageRoute: DashboardMileageRoute,
  DashboardReceiptsRoute: DashboardReceiptsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRoadmapRoute: DashboardRoadmapRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface HelpdeskRouteChildren {
  HelpdeskIdeasRoute: typeof HelpdeskIdeasRoute
  HelpdeskSupportRoute: typeof HelpdeskSupportRoute
  HelpdeskIndexRoute: typeof HelpdeskIndexRoute
}

const HelpdeskRouteChildren: HelpdeskRouteChildren = {
  HelpdeskIdeasRoute: HelpdeskIdeasRoute,
  HelpdeskSupportRoute: HelpdeskSupportRoute,
  HelpdeskIndexRoute: HelpdeskIndexRoute,
}

const HelpdeskRouteWithChildren = HelpdeskRoute._addFileChildren(
  HelpdeskRouteChildren,
)

interface UsRouteChildren {
  UsContactRoute: typeof UsContactRoute
  UsFaqRoute: typeof UsFaqRoute
  UsIndexRoute: typeof UsIndexRoute
  UsArticlesSlugRoute: typeof UsArticlesSlugRoute
  UsArticlesIndexRoute: typeof UsArticlesIndexRoute
}

const UsRouteChildren: UsRouteChildren = {
  UsContactRoute: UsContactRoute,
  UsFaqRoute: UsFaqRoute,
  UsIndexRoute: UsIndexRoute,
  UsArticlesSlugRoute: UsArticlesSlugRoute,
  UsArticlesIndexRoute: UsArticlesIndexRoute,
}

const UsRouteWithChildren = UsRoute._addFileChildren(UsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaRoute: CaRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  HelpdeskRoute: HelpdeskRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UsRoute: UsRouteWithChildren,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
