// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      throw new Response(
        "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are set.",
        { status: 500 },
      );
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Response("Unauthorized: No request headers available", { status: 401 });
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Response("Unauthorized: No authorization header provided", { status: 401 });
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Response("Unauthorized: Only Bearer tokens are supported", { status: 401 });
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Response("Unauthorized: No token provided", { status: 401 });
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response("Unauthorized: Invalid token", { status: 401 });
    }

    if (!data.claims.sub) {
      throw new Response("Unauthorized: No user ID found in token", { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);

/**
 * Helpdesk-specific admin gate, layered on top of requireSupabaseAuth's
 * JWT verification. A valid Supabase session alone is not enough -- the
 * caller's user id must also appear in ADMIN_USER_IDS (a comma-separated
 * server-only env var, never VITE_-prefixed). Every /helpdesk server
 * function attaches this middleware directly; there is no other
 * enforcement boundary, since a client-side route guard cannot prevent
 * someone from calling the server functions directly.
 */
export const requireHelpdeskAdmin = createMiddleware({ type: "function" })
  .middleware([requireSupabaseAuth])
  .server(async ({ context, next }) => {
    const rawAllowlist = process.env.ADMIN_USER_IDS;

    if (!rawAllowlist) {
      throw new Response("Server misconfiguration: ADMIN_USER_IDS is not set.", { status: 500 });
    }

    const allowlist = rawAllowlist
      .split(",")
      .map((id) => id.trim())
      .filter(Boolean);

    if (!allowlist.includes(context.userId)) {
      throw new Response("Forbidden: this Supabase account is not an approved helpdesk admin.", {
        status: 403,
      });
    }

    return next();
  });
